### ISSUE TITLE
Push 1.2.1 to RubyGems

### ISSUE THREAD

**Issue by cyclotron3k** [RaVbaker/flickr#7]
Would you be able to push v1.2.1 to Ruby Gems? The current version on there is a decade old, is sending credentials over HTTP instead of HTTPS, and doesn't seem to work.

**Comment by RaVbaker** [comment]
It's already there but you're looking at wrong gem... I cannot manage and maintain the `flickr` gem but I do created a separate one called `flickr.rb` please look here: https://rubygems.org/gems/flickr.rb 

It has 1.2.1 there already.

**Comment by cyclotron3k** [comment]
Oh sorry, my mistake.
